* issues with outline
** TODO Determine appropriate distribution for $\beta SI$
** TODO Put something meaningful in something somethign population size
** TODO Ensure all citations are filled in
** TODO Say something about why we want to use agent based models other than 'because it works'
** TODO Take out stochastic vs deterministic parts
** TODO Add motivation
** OPEN Combine with outline from meeting with justin (on laptop)
   Leaving Methods out for now.  Want to commit current before making changes.
** TODO Look up names in causal inference literature for simulating what would happen if we had intervened in this epidemic vs what would happen if we intervened in a similar epidemic.
** TODO Read chapter 6.6 of Mathematics of Epidemics on Networks pg 251
* Introduction
** Introduce Problem
*** Interventions
    Infectious diseases are a major global public health problem.
    When and how to intervene against an emerging infection is one of the fundamental questions in epidemiology, around which much work is centered. \cite{}
    There are a variety of methods used to determine when and how to intervene, including \cite{}.
    Generally when people address this question with models, they use a variety of simulation based methods.
    However, many of these approaches have low statistical power, and are not geared towards answering certain important questions (i.e. How often will this intervention cause more cases?).
*** Effects of Interventions - Counterfactual question
    In order to determine the effect of an intervention, we often want to compare what will happen if we perform the intervention with what will happen if we don't perform the intervention.
    These types of questions are known as counterfactuals.
    One problem with answering these types of questions, is that in reality you either do or don't perform the intervention, and the can't observe the other option.
    Even in simulations, existing methods have this property.
    They simulate disease occurrances strictly with or without the intervention and compare the two.
*** Problems with existing results
    Other approaches simulate separate epidemics with and without interventions, differences between these simulated epidemics include stochastic variation of the model.
    This approach has poor statistical power, since any stochasticity of the model contributes to error bounds on estimates.
    Additionally, the models variation can cause otherwise impossible effects to occur, like treatment increasing the number of cases observed with reasonable probability.
***** Examples from literature
*** Our method
    We want to simulate a single simulation with and without the intervention at the same time.
    This approach will eliminate the effects of the model error, while retaining any stochastic effects of the intervention.
    In order to allow a single simulation to have and not have the intervention, we have to simulate all the events that occur in either one.
    There may be events that don't occur in the non-intervention case that do occur in the intervention case, and vice versa.
    Then, for that simulation, we can measure the effect of the intervention.
    If we then simulate many times, we can see the distribution of our measurements.
* Methods
** Motivation
*** Compartmental Models
    Compartmental models are a standard in disease modeling \cite{}.
    There are a number of results where researchers perform counterfactual analysis on compartmental models \cite{}.
    There would be more results, except that the power of the standard way to do these analyses is low \cite{}.
    
** Example (Influenza)
*** SIR Model
    We use a standard short compartmental model for influenza \cite{}.
    There are compartments for susceptible, infected, and recovered.
    People move between these compartments at a rate determined by $\beta$, the force of infection, and $\gamma$ the recovery rate.
    This model is only valid for a short time scale, so we do not include births or deaths.
***** Figure: SIR Model diagram
    
*** Agent Perspective
**** Why we need stochasting models
     Our goal is to eliminate process error to improve power, but so far the models described are deterministic (and therefore have no process error).
     One could say that given a deterministic model, and a deterministic intervention, the effect of the intervention falls out cleanly.
     However, deterministic models are not widely used in the field \cite{}.
     Additionally, deterministic models cannot address a main question of interest, "How well is this intervention working?"
     
**** Viewing SIR model as a stochastic model
     Our SIR model makes implicit assumptions.
     $\beta SI$ represents interactions between susceptible and infected individuals.
     $\gamma I$ represents the probability of recovery.
     Our deterministic differential equation is actually the expectation of a stochastic process.
     Something something population size
     $\beta SI$ is ...
     $\gamma I$ is the expectation of a binomial distribution.

**** Agent Based Versions
     Instead of modeling the number of susceptibles, infected, and recovered, we want to switch and model the state of each person in our population.
     We do this, because it works.
     Instead of a vector of the number of people in each compartment, we use a vector of the state of each person.
     Each susceptible person has a $\frac{\beta}{N}$ probability of becoming infected by each infected person at each time step.
     Each infected person has a $\gamma$ probability of recovering at each time step.
     
*** Simulating and Pruning
**** Conditional Probabilities
     We know the probability that a person recovers given that they are infected is $\gamma$.
     We know the probability that a person infects another person given that the first is susceptible and the second is infected is $\frac{\beta}{N}$.
     We can simulate from these distributions without knowing if the conditionals are satisfied.
     This is helpful, since we won't know a priori what the intervention affects and doesn't.
     To simulate, we draw uniformly randomly from $[0,1]$, and compare that to the probability.
     If the random draw is less than the probability, it happens.
     Otherwise, it does not happen.
     
**** Simulate all possible events
     We could account for every possible intervention by simulating every relevent conditional probability.
     Given a population size $N$, and number of time steps $T$, there are a finite number of things to simulate.
     For each time step, we need to simulate $N$ recovery probabilities, and $N^2$ infection probabilities.
     In total, we would need to simulate $N(N+1)T$ numbers.
     For a population of $4$ million, and daily time steps for a year, that would take almost $6$ million gigabytes of storage. %(4000000 * 4000001 * 365) * bytes = 5840001.46 gigabytes
     More complicated models with more compartments would take even more space.

**** Pruning simulated events
     For many interventions, not all simulations are necessary.
     By making some assumptions about the interventions, we can reduce the amount we need to store.
     We assume that the intervention can only increase the probability of infection.
     
*** Intervention
** General Framework
*** General Compartmental Model
*** Agent Based Conversion
*** Simulating and Pruning
**** Assumptions
*** Interventions
**** None
**** Vaccination
**** Treatment
**** Social Distancing
* Results
** Illustritave Simulations
*** SIR Model
*** SIS Model (maybe)
** Computational Concerns (Time/Space Complexity)
*** Current Implementation
*** Tradeoffs
** Mathematical Reduction in error (derived)
* Discussion
** Philosohpical Discussion of Question Answered
*** We often ask the question of what would happen if we had intervened in a previous epidemic.
*** We often answer the question of what would happen if we intervene in a epidemic similar to the previous one.
