dyn.load('~/svn/counterfactual/branches/R_compliant/src/new.counterfactual.so')
dyn.load('~/svn/counterfactual/branches/R_compliant/src/multiple_trials.so')
.C('main')
dyn.unload('~/svn/counterfactual/branches/R_compliant/src/multiple_trials.so')
dyn.unload('~/svn/counterfactual/branches/R_compliant/src/new.counterfactual.so')
