#' @export 
#' @name setup_counterfactual
#' @title setup_counterfactual
#' @description Run all possibly relevant transmissions for a
#'   particular differential equations model.
#' @param filename A string containing the desired output stub.
#'   Should contain a filepath (probably to a directory) where the
#'   output from the counterfactual should be stored.
#' @param init A numeric vector of the initial conditions for the
#'   model.  It should length equal to the number of variables in the
#'   differential equations model, and each value should be the
#'   initial number of people in that compartment.
#' @param trans A matrix containing the state transitions that happen
#'   independent of any human interactions.  This matrix should be
#'   n by n, where n is the number of compartments. \code{trans[i,j]}
#'   should be the probability of transitioning from state \code{i} to
#'   state \code{j} at every time step.
#' @param inter An array containing the state transitions that happen
#'   as a result of human interactions.  This array should be n by n
#'   by n, where n is the number of compartments. \code{trans[i,j,k]}
#'   should be the probability of someone in state i having an
#'   interaction with a particular person in state \code{j}, which
#'   causes them to transition to state \code{k} at each time step.
#' @param ntime  The number of timesteps to run the simulation over.
#' @param ntrial The number of independent simulations to run.  The 
#'   differential equation is converted to a stochastic process when
#'   making it agent based, and so multiple trials are recommended.
#' @return This function generates \code{2*ntrial} files where
#'   determined by \code{filename}
#' @useDynLib cfepi setupCounterfactualAnalysis
setup_counterfactual <- function(filename,init,inter,trans,ntime,ntrial = 1000){
  .Call('setupCounterfactualAnalysis',
    filename,
    init,
    inter,
    trans,
    ntime,
    ntrial,
    PACKAGE='cfepi'
  )
}

#' @export 
#' @name run_scenario
#' @title run_scenario
#' @description Using a previously setup counterfactual, run a
#'   particular scenario.
#' @param filename A string containing the desired output stub.
#'   Should be the same argument that was passed to
#'   \code{setup_counterfactual}.
#' @param intervention_name A string containing a unique name for the
#'   intervention.  Any interventions with the same name will use the 
#'   same files, so take care not to overwrite an intervention by
#'   mistake
#' @param init A numeric vector of the initial conditions for the
#'   model.  It should length equal to the number of variables in the
#'   differential equations model, and each value should be the
#'   initial number of people in that compartment.  Should be the same
#'   argument that was passed to \code{setup_counterfactual}.
#' @param beta_type One of "None" or "Flat".
#'   "None" means that the intervention should not reduce
#'   transmissibility.
#'   "Flat" means that the intervention should reduce transmissibility
#'   by a constant \code{rate} after a certain \code{start_time}.
#' @param susceptible_type One of "None" or "Single".
#'   "None" means that the intervention should not eliminate
#'   susceptibles
#'   "Single" means that the intervention should eliminate susceptibles
#'   at a single \code{start_time} moving \code{rate} of them from 
#'   state \code{from_state} to state \code{to_state}.
#' @param beta_pars The parameters to use for the transmission
#'   reduction function.  This should be a list.
#' @param susceptible_pars the parameters to use for the susceptible 
#'   elimination function.  This should be a list.
#' @param ntime  The number of timesteps to run the simulation over.
#'   Should be the same argument that was passed to
#'   \code{setup_counterfactual}
#' @param ntrial The number of independent simulations to run.  The 
#'   differential equation is converted to a stochastic process when
#'   making it agent based, and so multiple trials are recommended.
#'   Should be the same argument that was passed to 
#'   \code{setup_counterfactual}
#' @return This function returns a data.frame one column for each
#'   state and one column for the simulation number.  It has one row
#'   for each time step, and the values are the number of people in
#'   that state at that time.
#' @useDynLib cfepi runIntervention
run_scenario <- function(filename,intervention_name,init,beta_type,susceptible_type,beta_pars,susceptible_pars,ntime,ntrial = 1000){
  .Call('runIntervention',
    filename,
    intervention_name,
    init,
    beta_type,
    susceptible_type,
    beta_pars,
    susceptible_pars,
    ntime, 
    ntrial,
    PACKAGE='cfepi'
  )
}

#' @export
#' @name clean_all_files
#' @title clean_all_files
#' @description remove files generated by setup_counterfactual and run_scenario
#' @param filename The same file stub argument given to setup_counterfactual
#' @param careful Whether to prompt before deleting files
clean_all_files <- function(filename,careful=TRUE){
  clean_run_files(filename,careful)
  clean_setup_files(filename,careful)
}
clean_setup_files <- function(filename,careful = TRUE){
  stub = basename(filename)
  path = dirname(filename)
  all_files = list.files(path)
  all_files = all_files[grepl(pattern=paste(stub, "[.].[.]0[.].*[.]dat", sep = ""),all_files)]
  if(length(all_files) > 0){
    if(!careful){
      file.remove(paste(path,all_files,sep='/'))
      return();
    }
    key = readline(prompt = paste("This operation will remove",length(all_files),"files.  Confirm [y/n]?"))
    if(key == 'y'){
      file.remove(paste(path,all_files,sep='/'))
      return()
    }
    warning("Files not removed")
  }
}

clean_run_files <- function(filename,careful=TRUE){
  stub = basename(filename)
  path = dirname(filename)
  all_files = list.files(path)
  all_files = all_files[grepl(pattern=paste(stub, "[.].*[.].*[.].*[.]csv", sep = ""),all_files)]
  ## Path weirdness to follow possibly?
  if(length(all_files) > 0){
    if(!careful){
      file.remove(paste(path,all_files,sep='/'))
      return();
    }
    key = readline(prompt = paste("This operation will remove",length(all_files),"files.  Confirm [y/n]?"))
    if(key == 'y'){
      file.remove(paste(path,all_files,sep='/'))
      return()
    }
    warning("Files not removed")
  }
}
