#' @export
#' @name clean_all_files
#' @title clean_all_files
#' @description remove files generated by setup_counterfactual and run_scenario
#' @param filename The same file stub argument given to setup_counterfactual
#' @param careful Whether to prompt before deleting files
clean_all_files <- function(filename,careful=TRUE){
  clean_run_files(filename,careful)
  clean_setup_files(filename,careful)
}
clean_setup_files <- function(filename,careful = TRUE){
  stub = basename(filename)
  path = dirname(filename)
  all_files = list.files(path)
  all_files = all_files[grepl(pattern=paste(stub, "[.].[.]0[.].*[.]dat", sep = ""),all_files)]
  if(!careful){
    file.remove(paste(path,all_files,sep='/'))
    return();
  }
  key = readline(prompt = paste("This operation will remove",length(all_files),"files.  Confirm [y/n]?"))
  if(key == 'y'){
    file.remove(paste(path,all_files,sep='/'))
    return()
  }
  warning("Files not removed")
}

clean_run_files <- function(filename,careful=TRUE){
  stub = basename(filename)
  path = dirname(filename)
  all_files = list.files(path)
  all_files = all_files[grepl(pattern=paste(stub, "[.].*[.].*[.].*[.]csv", sep = ""),all_files)]
  if(!careful){
    file.remove(all_files)
    return();
  }
  key = readline(prompt = paste("This operation will remove",length(all_files),"files.  Confirm [y/n]?"))
  if(key == 'y'){
    file.remove(all_files)
    return()
  }
  warning("Files not removed")
}
